### ISSUE TITLE
Modules usage

### ISSUE THREAD

**Issue by guybedford** [flowtype/flow-inspect#2]
I'm probably just doing something silly here misunderstanding flow, but I was wondering why this returns empty:

a.js
```javascript
import {p} from './b.js';

p();
```

b.js
```javascript
export function p () {
  return 'hello world';
}
```

Should this sort of modular case not work out the box? Or is the whole point that dump-types will only act on a single file at a time?

**Comment by thejameskyle** [comment]
Did you add the `// @flow` pragma comments at the top of each file? I'm not having this problem.

**Comment by guybedford** [comment]
@thejameskyle ahh sweet, thanks for taking the time to help a flow noob :)
